server:
  port: 8080
spring:
  # thymeleaf配置
  thymeleaf:
    #是否开启缓存
    cache: false
    enabled: true
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  # druid数据源
  datasource:
    url: jdbc:mysql://127.0.0.1
# mybatis配置
mybatis:
  type-aliases-package: com.rogue.gbf.gbfdemo.domain
  configuration:
    #把下划线转换成驼峰
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
  # 扫描mybatis的mapper和xml配置文件路径
  mapper-locations: classpath:com/rogue/gbf/gbfdemo/dao/*.xml